### ISSUE TITLE
请问TypeError: can only join an iterable需要怎么解决

### ISSUE THREAD

**Issue by gonggtao** [GlassyWing/text-detection-ocr#16]
我将densenet_predict.py中的image_path默认进行了设置
parser.add_argument("--image_path", help="图像位置",
default='E:\\Python\\Recognition\\dlocr\\picture\\1.jpg')
结果运行报了错，请问怎么办
Traceback (most recent call last):
  File "E:/Python/Recognition/dlocr/densenet_predict.py", line 37, in <module>
    print('\n'.join(densenet.predict(image_path, id_to_char)[1]))
TypeError: can only join an iterable

**Comment by GlassyWing** [comment]
这是一个bug:sweat_smile:，把37行改为:print(densenet . predict ( image _ path , id _ to _ char )[0])
