### ISSUE TITLE
我用ctpn去检测身份证上的文本，似乎效果不理想

### ISSUE THREAD

**Issue by white2018** [GlassyWing/text-detection-ocr#3]

**Comment by GlassyWing** [comment]
CTPN的效果还可以接受，造成效果不理想的原因或许是因为：用于训练densenet网络的图片全为白底黑字，而身份证上的文字颜色不总是黑色。

**Comment by white2018** [comment]
ctpn训练情况和你的训练过程差不多
![image](https://user-images.githubusercontent.com/26728432/49140458-474c5f00-f32f-11e8-9c98-e8345b9de5f0.png)

下面是测试效果
![image](https://user-images.githubusercontent.com/26728432/49140545-78c52a80-f32f-11e8-8b8b-b0856982192c.png)

**Comment by white2018** [comment]
@GlassyWing 能帮忙看看我的代码吗？告诉下邮箱？谢谢谢谢

**Comment by GlassyWing** [comment]
你可能修改了代码，你可以试试程序里提供的CTPN的权重文件，测试一下，这是我测试的结果：
![007_labeled](https://user-images.githubusercontent.com/17000429/50065265-a1369b00-01f0-11e9-8646-b341a115b2eb.jpg)

**Comment by white2018** [comment]
> 你可能修改了代码，你可以试试程序里提供的CTPN的权重文件，测试一下，这是我测试的结果：
> ![007_labeled](https://user-images.githubusercontent.com/17000429/50065265-a1369b00-01f0-11e9-8646-b341a115b2eb.jpg)

@GlassyWing 我试了一下你提供的权重文件，以及我训练的权重文件（python2.7环境下训练），发现python版本对模型预测的影响很大。如果用python2.7环境进行预测的话，效果都不好；但是用python3.6环境进行预测，效果很不错。不知道深层次的原因是什么

多谢多谢
