### ISSUE TITLE
叠词丢字问题

### ISSUE THREAD

**Issue by shihaoyin** [GlassyWing/text-detection-ocr#4]
识别结果中重叠字会出现丢字的现象，如“2003”，识别出的结果为“203”；“共和国国家”识别结果为“共和国家”。请问这个问题有没有解决思路，感谢作者开源！

**Comment by GlassyWing** [comment]
请提供问题图片用于还原问题

**Comment by GlassyWing** [comment]
这是解码错误，已修复。
