### ISSUE TITLE
数据标签

### ISSUE THREAD

**Issue by ling20180713** [GlassyWing/text-detection-ocr#5]
请问densenet 识别的数据标签是怎么制作的

**Comment by GlassyWing** [comment]
图片是用中英文语料生成的，大小固定为(280, 32)。标签文件中每一行是，“图片名 \t 文本标签” 的格式，文本标签表示的是每一个字在字典中的顺序。这里的数据集是直接从https://github.com/YCG09/chinese_ocr获取的，至于如何生成图片，参考https://github.com/Sanster/text_renderer

**Comment by ling20180713** [comment]
已经生成了图片及文字内容的txt文件,使得文本标签表示的是每一个字在字典中的顺序，这个生成文本标签的代码应该怎么编写，请大神指教
