### ISSUE TITLE
使用ctpn做训练时内存很快耗尽，有警告

### ISSUE THREAD

**Issue by magicnian** [GlassyWing/text-detection-ocr#6]
`D:\python3\lib\site-packages\tensorflow\python\ops\gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "`
报错信息如上
@GlassyWing

**Comment by GlassyWing** [comment]
ctpn为了识别大小不同的图片，并没有固定图片大小，所以这个警告是正常的，简单的说图片太大的话的确会造成oom，所以最好显存有11g以上

**Comment by magicnian** [comment]
> ctpn为了识别大小不同的图片，并没有固定图片大小，所以这个警告是正常的，简单的说图片太大的话的确会造成oom，所以最好显存有11g以上

嗯，感谢回复，我把图片做压缩后就没有这个问题了，确实是图片太大导致的

**Comment by magicnian** [comment]
> `D:\python3\lib\site-packages\tensorflow\python\ops\gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory. "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "`
> 报错信息如上
> @GlassyWing

贴个以上相关警告的解决方法（如果显存够大请无视），如果训练样本数据无法做处理，可以尝试以下的方法
https://stackoverflow.com/questions/35892412/tensorflow-dense-gradient-explanation
